payum:
#    storages:
#        Payum\Core\Model\Payment:
#            filesystem:
#                storage_dir: '%kernel.root_dir%/Resources/payments'
#                id_property: number
#
#    security:
#        token_storage:
#            Payum\Core\Model\Token:
#                filesystem:
#                    storage_dir: '%kernel.root_dir%/Resources/gateways'
#                    id_property: hash

    security:
        token_storage:
            App\Entity\PaymentToken: { doctrine: orm }

    storages:
        App\Entity\Payment: { doctrine: orm }

    gateways:
        offline:
            factory: offline
        paypal_express_checkout:
            factory: paypal_express_checkout
            username: '%env(PAYPAL_USERNAME)%'
            password: '%env(PAYPAL_PASSWORD)%'
            signature: '%env(PAYPAL_SIGNATURE)%'
            sandbox: true
